---
namespace: cisco
name: nd
# The version of the collection. Must be compatible with semantic versioning
version: 0.1.2
readme: README.md
authors:
  - "Lionel Hercot (@lhercot)"
  - "Cindy Zhao (@cizhao)"
  - "Alejandro de Alda (@adealdag)"
description: An Ansible collection for managing Cisco Nexus Dashboard
license_file: "LICENSE"
tags:
  - cisco
  - nd
  - aci
  - dcnm
  - orchestrator
  - multisite
  - insights
  - nexus
  - cloud
  - collection
  - networking
  - sdn
dependencies:
  "ansible.netcommon": "*"
repository: https://github.com/CiscoDevNet/ansible-nd
#documentation: https://docs.ansible.com/ansible/latest/scenario_guides/guide_nd.html
homepage: https://cisco.com/go/nexusdashboard
issues: https://github.com/CiscoDevNet/ansible-nd/issues
