---
- name: Run nd_compliance_requirement_config_manual integration suite
  hosts: nd
  gather_facts: false
  connection: ansible.netcommon.httpapi

  roles:
    - role: nd_compliance_requirement_config_manual
