---
- name: Run nd_interface_port_channel_trunk_host integration suite
  hosts: nd
  gather_facts: false
  connection: ansible.netcommon.httpapi

  roles:
    - role: nd_interface_port_channel_trunk_host
