---
# This playbook can be used to execute integration tests for
# the roles located in:
#
# REPO_ROOT/tests/integration/targets/dcnm_vrf/tests/dcnm/*.yaml
#
# Either:
#
# 1. Modify the following:
#
#    - The vars section below with details for your testing setup.
#    - dcnm_hosts.yaml in this directory
#
# 2. Run the tests
#
#    ansible-playbook dcnm_tests.yaml -i dcnm_hosts.yaml
#
# OR:
#
# 1. Modify ../../files/dynamic_inventory.py to align with your setup
#
#    This must contain the vars mentioned below and controller
#    info from dcnm_hosts.yaml (modified for your setup)
#
#  2. Run the tests
#
#     ansible-playbook dcnm_tests.yaml -i ../../files/dynamic_inventory.py
#
# 
- hosts: ndfc
  gather_facts: no
  connection: ansible.netcommon.httpapi
# Uncomment and modify if not using dynamic_inventory.py
# See the individual test yaml files for a description of
# how each var below is used in each test.  Some tests,
# for example, do not use interface_1.
  # vars:
    # ansible_it_fabric: {AK-VXLAN}
    # ansible_switch1: 10.122.84.58
    # ansible_switch2: 10.122.84.62
    # ansible_switch3: 10.122.84.201
    # switch_username: admin
    # switch_password: idgeR09!
    # deploy: false
    # testcase: "merged"

  # roles:
  #     - nd_manage_switches
    # standalone (non-msd) test vars
    # fabric_1: f1
    # switch_1: 192.168.1.2
    # switch_2: 192.168.1.3
    # switch_3: 192.168.1.4

    # multisite test vars
    # parent_fabric: pf1
    # child_fabric: cf1
    # child_switch_1: 192.168.1.2
    # child_switch_2: 192.168.1.3

    # common vars
    # interface_1: Ethernet1/1
    # interface_2a: Ethernet1/2
    # interface_3: Ethernet1/3
  
    ## Uncomment ONE of the following testcases

    # To run all tests under standalone,
    # testcase: standalone/*
    # To run individual standalone tests,
    # testcase: standalone/<test_name>
    # Example:
    # testcase: standalone/deleted

    # To run all tests under standalone/self-contained-tests,
    # testcase: standalone/self-contained-tests/*
    # To run individual self-contained tests,
    # testcase: standalone/self-contained-tests/<test_name>
    # Example:
    # testcase: standalone/self-contained-tests/scale

    # To run all tests under multisite,
    # testcase: msd/*
    # To run individual multisite tests,
    # testcase: msd/<test_name>
    # Example:
    # testcase: msd/sanity

    # To run all tests under multicluster,
    # testcase: mcfg/*
    # To run individual multicluster tests,
    # testcase: mcfg/<test_name>
    # Example:
    # testcase: mcfg/sanity



  tasks:
    # - name: Switches Add
    #   cisco.nd.nd_manage_switches:
    #     fabric: jeet_test
    #     state: merged
    #     config_actions:
    #       save: true
    #       deploy: true
    #       type: switch
    #     config:
    #       - seed_ip: 192.168.10.201
    #         username: admin
    #         password: Admin!@#
    #         role: leaf
    #         preserve_config: false
    #       - seed_ip: 192.168.10.202
    #         username: admin
    #         password: Admin!@#
    #         role: leaf
    #         preserve_config: false
    #         # poap:
    #         #   serial_number: 9HVHRQ563JM
    #         #   hostname: poap-l
    #   # check_mode: true
    #   register: result

  #         - seed_ip: 10.122.84.62
  #           username: admin
  #           password: idgeR09!
  #           role: leaf
  #           preserve_config: false
  #         # - seed_ip: 10.122.84.206
  #         #   username: admin
  #         #   password: idgeR09!
  #         #   role: spine
  #         #   poap:
  #         #     serial_number: 9HVHRQ563JM
  #         #     hostname: poap-l
  #         #     # # config_data:
  #         #     # #   models:
  #         #     # #     - N9K-C93180YC-EX
  #         #     #   gateway: 10.122.84.1/24
  #         - seed_ip: 10.122.84.205
  #           username: admin
  #           password: idgeR09!
  #           role: leaf
  #           preprovision:
  #             serial_number: KAL1234ABCE
  #             model: N9K-C93180YC-EJ
  #             version: "10.3(1)"
  #             hostname: prepro-l
  #             config_data:
  #               models:
  #                 - N9K-C93180YC-EX
  #               gateway: 10.122.84.1/24
  #     register: result
